# Staff Chat - By Rodrigo R.

on_enable: "&7Staff chat enabled. Remember you can also use &b/sc [message] &7to send messages."
on_disable: "&7Staff chat disabled."
on_message: "&b[StaffChat] {server} &7{player}: {message}"
no_permission: "&cYou don't have permission to use this command."
error_console: "&cYou can't use this command in the console."
config_reload: "&7Config reloaded."

# Permissions:
# staffchat.use - Use staff chat (Enable, disable and recieve staff chat messages)
# staffchat.reload - Reload the config

# Hidden uses:
# /sc reload - Reload the config

# Use: /sc OR /staffchat

text_format: "captialize"
# "capitaize" -> Capitalize the placeholders (player, message, server)
# "lowercase" -> Lowercase the placeholders (player, message, server)
# "uppercase" -> Uppercase the placeholders (player, message, server)
# "raw -> Keep the placeholders as their original case